language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

os:
  - osx

env:
  global:
    - BUILD_REVISION=official
  matrix:
    - PLATFORM=android TARGET=release
    - PLATFORM=android TARGET=release_debug


before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then sudo apt-get update -qq; sudo apt-get install -y scons pkg-config build-essential upx-ucl; fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew update; brew install scons upx; fi;
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$PLATFORM" = "android" ]; then brew install android-sdk android-ndk gradle; export ANDROID_HOME=/usr/local/opt/android-sdk; export ANDROID_NDK_ROOT=/usr/local/opt/android-ndk; fi;
  - if [ "$PLATFORM" = "windows" ]; then sudo apt-get install -y mingw32 mingw-w64; fi;
  - if [ "$PLATFORM" = "x11" ]; then
      sudo apt-get install -y libx11-dev libxcursor-dev libasound2-dev libpulse-dev libfreetype6-dev libgl1-mesa-dev libglu1-mesa-dev libssl-dev libxinerama-dev libudev-dev;
      if [ "$BITS" = "32" ]; then
          sudo dpkg --add-architecture i386; sudo apt-get update -qq; sudo apt-get install -y --only-upgrade g++ gcc libstdc++6;
          sudo apt-get install -y gcc-multilib g++-multilib pkg-config:i386 libx11-dev:i386 libxcursor-dev:i386 libasound2-dev:i386 libpulse-dev:i386 libfreetype6-dev:i386 libgl1-mesa-dev:i386 libglu1-mesa-dev:i386 libssl-dev:i386 libxinerama-dev:i386 libudev-dev:i386;
      fi;
    fi;
  - if [ "$PLATFORM" = "javascript" ]; then
      brew update; brew install -v scons emscripten;
      emcc; sed -i "" s/^LLVM_ROOT.*/LLVM_ROOT='"\/usr\/local\/opt\/emscripten\/libexec\/llvm\/bin\/"'/ "$HOME/.emscripten";
      export EMSCRIPTEN_ROOT=`em-config EMSCRIPTEN_ROOT`;
    fi;


script:
  - cd godot
  - if [ "$PLATFORM" = "windows" -o "$PLATFORM" = "osx" ]; then
      if [ "$TOOLS" = "yes" ]; then scons -j2 platform=$PLATFORM CXX=$CXX tools=yes bits=$BITS target=release_debug;
      else scons -j2 platform=$PLATFORM CXX=$CXX tools=no bits=$BITS target=release;
           scons -j2 platform=$PLATFORM CXX=$CXX tools=no bits=$BITS target=release_debug > /dev/null;
      fi;
    fi;
  - if [ "$PLATFORM" = "x11" -o "$PLATFORM" = "server" ]; then
      if [ "$TOOLS" = "yes" ]; then scons -j2 platform=$PLATFORM CXX=$CXX tools=yes openssl=builtin use_static_cpp=yes bits=$BITS target=release_debug;
      else scons -j2 platform=$PLATFORM CXX=$CXX tools=no openssl=builtin use_static_cpp=yes bits=$BITS target=release;
           scons -j2 platform=$PLATFORM CXX=$CXX tools=no openssl=builtin use_static_cpp=yes bits=$BITS target=release_debug > /dev/null;
      fi;
    fi;
  - if [ "$PLATFORM" = "android" ]; then
      if [ "$TARGET" = "release" ]; then target_tag="opt"; else target_tag="opt.debug"; fi;
      scons -j2 platform=$PLATFORM CXX=$CXX target=$TARGET;
      scons -j2 platform=$PLATFORM CXX=$CXX target=$TARGET android_arch=x86 > /dev/null;
      mkdir -p platform/android/java/libs/{armeabi,x86};
      mv bin/libgodot.android.$target_tag.armv7.neon.dylib platform/android/java/libs/armeabi/libgodot_android.so;
      mv bin/libgodot.android.$target_tag.x86.dylib platform/android/java/libs/x86/libgodot_android.so;
      cd platform/android/java; ./gradlew build;
      cp build/outputs/apk/java-release-unsigned.apk ../../../bin/godot.android.$target_tag.apk;
    fi;
  - if [ "$PLATFORM" = "iphone" ]; then
      scons -j2 platform=$PLATFORM CXX=$CXX bits=32 target=$TARGET;
      scons -j2 platform=$PLATFORM CXX=$CXX bits=64 target=$TARGET > /dev/null;
    fi;
  - if [ "$PLATFORM" = "javascript" ]; then
      scons -j2 platform=$PLATFORM CXX=$CXX target=release;
      scons -j2 platform=$PLATFORM CXX=$CXX target=release_debug > /dev/null;
    fi;


before_deploy:
  - if [ "$PLATFORM" != "android" -a "$PLATFORM" != "iphone" -a "$PLATFORM" != "javascript" ]; then upx bin/godot*.$PLATFORM.opt.*; fi;
  - if [ "$PLATFORM" = "iphone" ]; then
      if [ "$TARGET" = "release" ]; then target_tag="opt"; else target_tag="opt.debug"; fi;
      lipo -create -arch armv7 bin/godot.iphone.$target_tag.32 -arch arm64 bin/godot.iphone.$target_tag.64 -output bin/godot.iphone.$target_tag.universal;
      rm -rf bin/godot.iphone.$target_tag.32*;
      rm -rf bin/godot.iphone.$target_tag.64*;
    fi;
  - if [ "$PLATFORM" = "javascript" ]; then
      cp tools/html_fs/godot.html .;
      cp tools/html_fs/godotfs.js .;
      for target_tag in opt opt.debug; do
        cp -f bin/godot.javascript.$target_tag.js godot.js;
        cp -f bin/godot.javascript.$target_tag.html.mem godot.mem;
        zip bin/godot.javascript.$target_tag.zip godot.js godot.mem godotfs.js godot.html;
        rm -f bin/godot.javascript.$target_tag.js;
        rm -f bin/godot.javascript.$target_tag.html*;
      done;
    fi;


deploy:
  provider: releases
  api_key:
    secure: tCFCHet6fgtf1+sgQEft4XTIfNH2JrqRx+YaatEfEEVNkHbY3SnRdtvcZeTeHc1LNpf6S0eU45RkBHeyN1Gna80Yiz8uep7rFuUTp5XtZsRfNecw/ebhPlyOEf3AhCVBJ3e3RxT2V1i/+8HyaWBisbXMZ1R+w07M3BxQrTpJflb7iSIXYTF//BxBtC1Atp7egDoU97OJfLSPEhPbjGhMoUuLTe7wmZqd7zK3DNTatL/pXefLN67N15dOra0LNgBHo1o6P4wcVBT2V+o9/TK5RAyUi5TqoudETgq2pBdAE558OuBbHh1dwDrs9b9ZbUC0mLautadiSbCkU0nLmYapaCKGr4+DpnZCxZYgzcYb5UPb6u6Rs3pY11JFtPYIXR2C1UJh4rpBIQa+F/eBKnw+QztnjfYWxJYq2T73CuFLgku89x99cVq7EiP0g/lZp64HxyENOcyL0FlWwjmq2vnr8BKNhDEVAXIUB1JsH8VshvndlgLhaRyRe+rkXnikLX8Nm6Z9V4pCjnRuCgiwZtYjxMTBhk30ZtXUg4uzCVmbvbUql8PPNrWDeq9yoUVe55kqU6DsxM1CEIou7Qcua2eeXcUkOGCgpXH4W0NXWBFo7Ze7FWHeKSHAcBeUrUpbiY75fcFdVjY/uUJaXQpem64Xm0O8GxK67CsBqAJahD1hxjc=
  file_glob: true
  file:
    - bin/godot*.$PLATFORM.opt.*
  skip_cleanup: true
  on:
    repo: GodotBuilder/godot-builds
    tags: true
